### ISSUE TITLE
Archive project

### ISSUE THREAD

**Issue by a-schild** [vineyardkoeln/churchtools-api#13]
Hello,

I think that we should archive this project, as it is no longer actively developed.

This project has taken over and is active
https://github.com/5pm-HDH/churchtools-api

**Comment by YetiCGN** [comment]
Nice! We are currently relaunching our site and once that's done I will retire this, but for now we still need the dependency for our currently running page.

**Comment by a-schild** [comment]
Yes,
we too have some projects which still use this library, but they will also be moved over to the 5pm-HDH library in the next months.

Don't delete the repo, but just Archive it, then everything is still readonly available, but no changes are allowed.
And put a pointer to the https://github.com/5pm-HDH/churchtools-api project on top of the Readme.md file ;)

![grafik](https://github.com/vineyardkoeln/churchtools-api/assets/1441009/f7eff7d5-ac2b-4ced-a259-09239c6eb3f5)
