### ISSUE TITLE
api2 missing in composer project

### ISSUE THREAD

**Issue by MR4online** [vineyardkoeln/churchtools-api#9]
when including the project via composer, api2 is missing

**Comment by YetiCGN** [comment]
You have to use the version "dev-master" for now since there is no release with API2 yet. @a-schild is working on that.

**Comment by YetiCGN** [comment]
I just released [0.5.1](https://github.com/vineyardkoeln/churchtools-api/releases) with a necessary fix (a feature actually, but the API can't be accessed anymore without it ...) which also contains the code for API2.
